### ISSUE TITLE
TEST FAILED: sst-test-elements -w "*simple*"

### ISSUE THREAD

**Issue by kaustubhcs** [sstsimulator/sst-elements#1940]
A new installation of SST and SST Elements 12.0.1 on our server following documentation provided failed the test.
Test command:
```
sst-test-elements -w "*simple*"
```
OUTPUT:
```
INFO: SST Test Engine Instantiated - Running tests on Registered Elements
INFO: Test Platform = UBUNTU 18.04
INFO: Running on Python Version = 3.8.13
INFO: TestEngine Version = --------------------------------------------------------------------------
[[53517,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: cray

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------
(12.0.1)
INFO: Available Cores = 256; Num Ranks = 1; Num Threads = 1
INFO: TestSuite wildcards to search for: testsuite_*simple*.py
INFO: Test scenarios to filter tests: NONE
INFO: SST Test Output Directory = /home/ktb/sst_test_outputs
INFO: Full colorized output can be obtained by running 'pip install blessings pygments'

=== TESTS STARTING ===================================================
testsuite_default_simpleComponents
    FAIL -- test_basic_clocks (testsuite_default_simpleComponents.testcase_simpleComponents) [0.505s]
    FAIL -- test_basic_links (testsuite_default_simpleComponents.testcase_simpleComponents) [0.502s]
    FAIL -- test_basic_params (testsuite_default_simpleComponents.testcase_simpleComponents) [0.479s]
    FAIL -- test_basic_statistics_0 (testsuite_default_simpleComponents.testcase_simpleComponents) [0.516s]
    FAIL -- test_basic_statistics_1 (testsuite_default_simpleComponents.testcase_simpleComponents) [0.536s]
    FAIL -- test_basic_statistics_2 (testsuite_default_simpleComponents.testcase_simpleComponents) [0.504s]
    FAIL -- test_example_0 (testsuite_default_simpleComponents.testcase_simpleComponents) [0.490s]
    FAIL -- test_example_1 (testsuite_default_simpleComponents.testcase_simpleComponents) [0.495s]

======================================================================
=== TESTS FINISHED ===================================================
======================================================================

======================================================================
FAIL: test_basic_clocks (testsuite_default_simpleComponents.testcase_simpleComponents)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 28, in test_basic_clocks
    self.simple_components_template("basicClocks")
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 92, in simple_components_template
    self.assertTrue(cmp_result, "Sorted Output file {0} does not match sorted Reference File {1}".format(cmpfile, reffile))
AssertionError: False is not true : Sorted Output file /home/ktb/sst_test_outputs/tmp_data/basicClocks.cmp does not match sorted Reference File /home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/refFiles/basicClocks.out

======================================================================
FAIL: test_basic_links (testsuite_default_simpleComponents.testcase_simpleComponents)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 31, in test_basic_links
    self.simple_components_template("basicLinks")
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 92, in simple_components_template
    self.assertTrue(cmp_result, "Sorted Output file {0} does not match sorted Reference File {1}".format(cmpfile, reffile))
AssertionError: False is not true : Sorted Output file /home/ktb/sst_test_outputs/tmp_data/basicLinks.cmp does not match sorted Reference File /home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/refFiles/basicLinks.out

======================================================================
FAIL: test_basic_params (testsuite_default_simpleComponents.testcase_simpleComponents)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 34, in test_basic_params
    self.simple_components_template("basicParams")
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 92, in simple_components_template
    self.assertTrue(cmp_result, "Sorted Output file {0} does not match sorted Reference File {1}".format(cmpfile, reffile))
AssertionError: False is not true : Sorted Output file /home/ktb/sst_test_outputs/tmp_data/basicParams.cmp does not match sorted Reference File /home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/refFiles/basicParams.out

======================================================================
FAIL: test_basic_statistics_0 (testsuite_default_simpleComponents.testcase_simpleComponents)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 37, in test_basic_statistics_0
    self.simple_components_template("basicStatistics0")
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 92, in simple_components_template
    self.assertTrue(cmp_result, "Sorted Output file {0} does not match sorted Reference File {1}".format(cmpfile, reffile))
AssertionError: False is not true : Sorted Output file /home/ktb/sst_test_outputs/tmp_data/basicStatistics0.cmp does not match sorted Reference File /home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/refFiles/basicStatistics0.out

======================================================================
FAIL: test_basic_statistics_1 (testsuite_default_simpleComponents.testcase_simpleComponents)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 40, in test_basic_statistics_1
    self.simple_components_template("basicStatistics1")
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 92, in simple_components_template
    self.assertTrue(cmp_result, "Sorted Output file {0} does not match sorted Reference File {1}".format(cmpfile, reffile))
AssertionError: False is not true : Sorted Output file /home/ktb/sst_test_outputs/tmp_data/basicStatistics1.cmp does not match sorted Reference File /home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/refFiles/basicStatistics1.out

======================================================================
FAIL: test_basic_statistics_2 (testsuite_default_simpleComponents.testcase_simpleComponents)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 43, in test_basic_statistics_2
    self.simple_components_template("basicStatistics2")
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 92, in simple_components_template
    self.assertTrue(cmp_result, "Sorted Output file {0} does not match sorted Reference File {1}".format(cmpfile, reffile))
AssertionError: False is not true : Sorted Output file /home/ktb/sst_test_outputs/tmp_data/basicStatistics2.cmp does not match sorted Reference File /home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/refFiles/basicStatistics2.out

======================================================================
FAIL: test_example_0 (testsuite_default_simpleComponents.testcase_simpleComponents)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 22, in test_example_0
    self.simple_components_template("example0")
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 92, in simple_components_template
    self.assertTrue(cmp_result, "Sorted Output file {0} does not match sorted Reference File {1}".format(cmpfile, reffile))
AssertionError: False is not true : Sorted Output file /home/ktb/sst_test_outputs/tmp_data/example0.cmp does not match sorted Reference File /home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/refFiles/example0.out

======================================================================
FAIL: test_example_1 (testsuite_default_simpleComponents.testcase_simpleComponents)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 25, in test_example_1
    self.simple_components_template("example1")
  File "/home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/testsuite_default_simpleComponents.py", line 92, in simple_components_template
    self.assertTrue(cmp_result, "Sorted Output file {0} does not match sorted Reference File {1}".format(cmpfile, reffile))
AssertionError: False is not true : Sorted Output file /home/ktb/sst_test_outputs/tmp_data/example1.cmp does not match sorted Reference File /home/ktb/scratch/src/sst-elements-library-12.0.1/src/sst/elements/simpleElementExample/tests/refFiles/example1.out

----------------------------------------------------------------------
Ran 8 tests in 4.032s

FAILED (failures=8)

=== TEST RESULTS BREAKDOWN ===========================================

testsuite_default_simpleComponents.testcase_simpleComponents
 - FAILED  : test_basic_clocks (testsuite_default_simpleComponents.testcase_simpleComponents)
 - FAILED  : test_basic_links (testsuite_default_simpleComponents.testcase_simpleComponents)
 - FAILED  : test_basic_params (testsuite_default_simpleComponents.testcase_simpleComponents)
 - FAILED  : test_basic_statistics_0 (testsuite_default_simpleComponents.testcase_simpleComponents)
 - FAILED  : test_basic_statistics_1 (testsuite_default_simpleComponents.testcase_simpleComponents)
 - FAILED  : test_basic_statistics_2 (testsuite_default_simpleComponents.testcase_simpleComponents)
 - FAILED  : test_example_0 (testsuite_default_simpleComponents.testcase_simpleComponents)
 - FAILED  : test_example_1 (testsuite_default_simpleComponents.testcase_simpleComponents)

=== TEST RESULTS SUMMARY =============================================

Tests Run            = 8
----------------------------------------
Passing              = 0
Failures             = 8
Skipped              = 0
Errors               = 0
Expected Failures    = 0
Unexpected Successes = 0
Testing Notes        = 0
----------------------------------------------------------------------
-- Total Test Time = 0 Hours, 0 Minutes, 4.073 Seconds --

====================
== TESTING FAILED ==
====================

======================================================================

```

**Comment by kaustubhcs** [comment]
One of the great wonders of the software community is trailing debug messages in production code.

Fixed it by disabling OpenMPI from leaving breadcrumbs debug messages in the output.
You can do so by exporting the environment variable:
```
OMPI_MCA_btl_base_warn_component_unused=0
```
