### ISSUE TITLE
MemHierarchy Prefetch Params Test Fails on POWER7

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-elements#723]
Running serially seems OK, running threaded is a problem

```/home/sdhammo/sst/20170727-p7/core/bin/sst -n 4 testPrefetchParams.py```

Output:

```
#0  0x00000000100a0614 in SST::Event::execute (this=0x3fff9ef0f868) at event.cc:30
#1  0x00000000100d02c0 in SST::Simulation::run (this=0x3fffa00008c0) at simulation.cc:530
#2  0x00000000100638e0 in start_simulation (tid=<optimized out>, info=..., barrier=...) at main.cc:330
#3  0x00000000100640d8 in _M_invoke<0ul, 1ul, 2ul> (this=<optimized out>) at /usr/include/c++/4.8.2/functional:1732
#4  operator() (this=<optimized out>) at /usr/include/c++/4.8.2/functional:1720
#5  std::thread::_Impl<std::_Bind_simple<void (*(unsigned int, std::reference_wrapper<SimThreadInfo_t>, std::reference_wrapper<SST::Core::ThreadSafe::Barrier>))(unsigned int, SimThreadInfo_t&, SST::Core::ThreadSafe::Barrier&)> >::_M_run() (this=<optimized out>) at /usr/include/c++/4.8.2/thread:115
#6  0x00003fffb7b0bed4 in ?? () from /lib64/libstdc++.so.6
#7  0x00003fffb7f0c26c in .start_thread () from /lib64/libpthread.so.0
#8  0x00003fffb77d7440 in .__clone () from /lib64/libc.so.6
```

**Comment by nmhamster** [comment]
Investigation seems to suggest these are most likely memory pool issues in the core. Closing.
